### ISSUE TITLE
Convert to Org?

### ISSUE THREAD

**Issue by kaushalmodi** [myTerminal/world-of-emacs#1]
Reading through few parts of this great write-up, I wondered if you'd like to convert this to Org, of course if you are comfortable editing Org. 

Few reasons:

- Users can clone this repo, and read/search from the convenience of org-mode.
  - To help with that, it would be even more awesome to combine the whole thing into a single Org file. 
- The Org markup also will be rendered fine in GitHub (even Gitlab too).
- This can become a wonderful demonstration of Org. Eventually it's World of Emacs :)
- *My insidious plan to then convert that Org file to a little static website using `ox-hugo` + Hugo.*

If you are up for it, I can help with the Markdown -> 1 Org file conversion.

**Comment by myTerminal** [comment]
Converting to org sounds like a good idea. I see the clear advantages there.

Regarding merging into a single page, I originally made it into multiple pages to hide details at the start. I have seen many such documents on GitHub that are a single page but are too long and overwhelming with details when first viewed. I also wanted to present a systematic set of steps to the newbies. We can still merge it into one and it would help not only in direct viewing but also updating the document. What do you say?

**Comment by kaushalmodi** [comment]
> Regarding merging into a single page, I originally made it into multiple pages to hide details at the start.

If we generate a static site, we can have it have the same page structure; just that the source Org file will be a single file.

> We can still merge it into one and it would help not only in direct viewing but also updating the document. What do you say?

That's what I was saying :) I can work on the conversion to a single Org file. Let me know if you'd like to do that (I see that you self-assigned this issue), so that we don't duplicate the efforts.

**Comment by myTerminal** [comment]
I'll take care of the conversion, should be done by tonight. You can probably help in the review if possible.

**Comment by kaushalmodi** [comment]
Sure, no problem. Thanks.

**Comment by myTerminal** [comment]
Done. Could you review?

**Comment by kaushalmodi** [comment]
I skimmed through the document and it looks great. Thanks for doing this.

The only comments I have are:
- Pending update of the order of package repos.
- I can only suggest using auto-filling to a standard fill-column of 70 chars so that:
  1. The Org file is better readable on Emacs in raw form (the auto-filling anyways doesn't matter to the exporters).
  2. The diffs will be less noisy. Take the below paragraph as an example.. to any diff tool, the whole thing is a "line". So if anything changes anywhere in that "line", the diff tool will mark that line as changed. On the other hand, if auto-filling is done, each filled line will now be that "line".. so glancing at diffs and looking at what changed will be quicker.

  Example:
  ```
  The next thing that you can do is to help others learn Emacs. There are various forms of training material available: posts and articles about tips and tricks and individual experiences with Emacs, GitHub projects containing documentation (like this one), websites specifically created to host content about Emacs, YouTube training videos, etc.
   ```

  vs

    ```
    The next thing that you can do is to help others learn Emacs. There
    are various forms of training material available: posts and articles
    about tips and tricks and individual experiences with Emacs, GitHub
    projects containing documentation (like this one), websites
    specifically created to host content about Emacs, YouTube training
    videos, etc.
    ```

---

I tend to have this at the bottom of all my Org files:

```org
* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# fill-column: 70
# eval: (auto-fill-mode 1)
# End:
```

**Comment by myTerminal** [comment]
I have taken care of your review comments.

I have still kept marmalade-repo at the top of the list of options to publish packages as it is the easiest one to get one's packages to. To download packages, I have placed it as the last option for obvious reasons.

Kindly let me know your thoughts.

**Comment by kaushalmodi** [comment]
Thank you. I will find some time over the next week to use this Org file to generate a static site using ox-hugo + hugo.

**Comment by myTerminal** [comment]
Sounds great!

**Comment by myTerminal** [comment]
@kaushalmodi, can we close this one?

**Comment by kaushalmodi** [comment]
Yes. I didn't get time to work on this afterall. 

Thanks for checking.
