### ISSUE TITLE
Why Marmalade?

### ISSUE THREAD

**Issue by kaushalmodi** [myTerminal/world-of-emacs#2]
I seriously doubt that Marmalade is much active these days. Melpa, I believe, is a superset of Marmalade. 

On [this page][1], Marmalade is mentioned as the first option. If not removed altogether, can that be moved as the last option?

These days, I see more contributors becoming aware of and willing to assign the copyright to FSF. If more people become aware of that, we get more active contributors for Emacs core AND GNU Elpa. 

GNU Elpa should be a part of that list.. I know of many packages that are on GNU Elpa, but not on Melpa. 

[1]: https://github.com/myTerminal/world-of-emacs/blob/master/03-give-back/01-write-your-own-extensions.md

**Comment by myTerminal** [comment]
You are correct: Nic Ferrier is too busy these days to maintain marmalade. However, there are many packages on marmalade that are not there on MELPA.

Let us keep a mention of marmalade-repo, but we can definitely move it down the list as you suggest. About GNU Elpa, is it not configured by default in Emacs? For publishing, I have never had an experience publishing packages over there. Can just 'anyone' do that? If you have pointers, any help would be appreciated.

**Comment by kaushalmodi** [comment]
> Let us keep a mention of marmalade-repo, but we can definitely move it down the list as you suggest.

OK

> About GNU Elpa, is it not configured by default in Emacs? 

It is.

> For publishing, I have never had an experience publishing packages over there. 

I don't have experience either, but I am about to submit `ox-hugo` to GNU Elpa too.

> Can just 'anyone' do that? If you have pointers, any help would be appreciated.

The *anyone* is qualified -- "**Anyone** who has assigned their copyright to FSF". The copyright assignment is a very easy process ..

You need to send an email to `assign@gnu.org` asking that you'd like to assign your copyrights to FSF. 

This is what I emailed them when I started with my FSF copyright assignment process:

> Hi,
> 
> I visited this site: https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html#Copyright-Papers
>
> I would like to contribute to GNU Emacs.
> 
> What are the copyright papers that I would need to sign?

And the process was over in a week, all via electronic media (email and PDF attachments).

[1]: http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/README

**Comment by myTerminal** [comment]
Good to know that it is even within reach to be able to publish packages to GNU ELPA.

Thanks for the info, that was helpful.

I have added a reference for that too now, you can find it in [this commit](https://github.com/myTerminal/world-of-emacs/commit/c1ce8fb883e3f0a3d7a3c560b5f324902b25a474#diff-34fa84eef454bfe99c737073e6d8b2b3).

**Comment by myTerminal** [comment]
This should have been take care of as a part of [issue 1](https://github.com/myTerminal/world-of-emacs/issues/1).

**Comment by kaushalmodi** [comment]
Thanks!
