### ISSUE TITLE
Mention Mastering Emacs

### ISSUE THREAD

**Issue by manuel-uberti** [myTerminal/world-of-emacs#3]
Great post, thanks for sharing.

You could mention both the website and the book by @mickeynp. They have been of invaluable help on my road to Emacs.

https://www.masteringemacs.org/

**Comment by manuel-uberti** [comment]
Closing here. Feel free to re-open if there is an interesting in doing this.

**Comment by manuel-uberti** [comment]
Oh, thank you! :+1:

**Comment by myTerminal** [comment]
I too have passed through the website a few times. Probably the only thing that made me not consider this one earlier was the price of the book. As of today it is $39.99, which is a bit expensive as compared to the other free sources mentioned in the guide.

I have added a mention though in my [commit](https://github.com/myTerminal/world-of-emacs/commit/29188e2e067ff8e6844ee37d5680af7e62b42597).

**Comment by manuel-uberti** [comment]
Yes, the book is not cheap, but technical books rarely are. :)

I guess we can close this issue now.

**Comment by myTerminal** [comment]
Thank you
